stages:
  - test

test:
  stage: test
  image: docker:24.0.9
  services:
    - docker:24.0.9-dind
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: App/coverage.cobertura.xml
  coverage: '/| atdd-v2-dotnet | \d+(?:\.\d+)?/'
  script:
    - apk add --no-cache docker-compose
    - cd App
    - ./ci-app-run.sh
    - ./ci-test.sh
