version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
#    volumes:
#      - ./data/mssql/:/var/opt/mssql
    environment:
      SA_PASSWORD: Dasasdfng3d1!@#
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      default:
        aliases:
          - mssql.tool.net

  mock-server:
    image: 'mockserver/mockserver:5.13.2'
    ports:
      - 1080:1080
    expose:
      - 1080
    command: [ "-serverPort", "1080", "-logLevel", "INFO" ]
    healthcheck:
      test: [ "CMD", "nc" ,"-z", "localhost", "1080" ]
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - mock-server.tool.net

  grpc-mock:
    #image: tkpd/gripmock:v1.12.1
    image: bavix/gripmock:2.6.8
    volumes:
      - ./:/proto
    ports:
      - '4771:4771'
      - '4770:4770'
    expose:
      - 4770
    command: [ '/proto/greeter.proto' ]
    networks:
      default:
        aliases:
          - grpc-mock.tool.net

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.3
    ports:
      - "9094:9094"
    expose:
      - 9094
      - 9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "dotnet.message:1:1,dotnet.data:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://:9092,OUTSIDE://kafka.tool.net:9094"
      KAFKA_LISTENERS: "INSIDE://:9092,OUTSIDE://kafka.tool.net:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    #      KAFKA_LOG_RETENTION_MS: 1000
    #      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - kafka.tool.net

  jdk:
    image: openjdk:11
    working_dir: /tmp/build/
    environment:
      GRADLE_USER_HOME: /tmp/tmp-user/.gradle
    volumes:
      - './e2e_test/:/tmp/build/'
      - 'gradle-user-home:/tmp/tmp-user/.gradle'
    command: tail -f /dev/null

  dotnet:
    build: .
    ports:
      - "10081:10081"
    entrypoint: ["./atdd-v2-dotnet"]
    environment:
      ASPNETCORE_ENVIRONMENT: E2e
    networks:
      default:
        aliases:
          - api.net

volumes:
  gradle-user-home:
    name: gradle_repo