// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/greeting.proto

// Protobuf Java Version: 3.25.2
package com.odde.atddv2.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.odde.atddv2.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
