// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/greeting.proto

// Protobuf Java Version: 3.25.2
package com.odde.atddv2.grpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.odde.atddv2.grpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
